import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header/Header";
import styles from "../styles/pages/Home.module.scss";

import Mouse from "../assets/icons/mouse.svg";
import Story from "../components/Story/Story";
import Theory from "../components/Theory/Theory";
import Manipulation from "../components/Manipulation/Manipulation";
import Debunk from "../components/Debunk/Debunk";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <section className={styles.hero}>
        <Image
          className={styles.heroImage}
          width={2268}
          height={4032}
          layout="fill"
          src="/images/space2.jpg"
          alt="space"
        />

        <div className={styles.heroContent}>
          <div className={styles.heroText}>
            <div className={styles.heroTitle}>
              <div className={styles.mask1}></div>
              <h1>Yes,</h1>
            </div>
            <div className={styles.heroTitle}>
              <div className={styles.mask2}></div>
              <h1>We've been there</h1>
            </div>
          </div>

          <div className={styles.heroShadow}></div>
          <div className={styles.moonContainer}>
            <div className={styles.moonShadow}></div>
            <Image
              className={styles.moon}
              src="/images/moon.png"
              alt="moon"
              width={500}
              height={500}
              layout="responsive"
            />
          </div>
        </div>
        <Mouse className={styles.mouse} />
      </section>
      <main className="page">
        <Story />
        <Theory />
        <Manipulation />
        <Debunk />
      </main>
    </div>
  );
}
